# Generated by Django 4.2.30 on 2026-04-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                (
                    "preferred_contact_phone",
                    models.CharField(blank=True, max_length=32),
                ),
                ("default_delivery_notes", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
