# Generated by Django 4.2.30 on 2026-04-21 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0002_alter_order_payment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("stripe", "Stripe")], default="stripe", max_length=24
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("cash_on_delivery", "Cash on delivery"),
                            ("card", "Card"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("requires_action", "Requires action"),
                            ("authorized", "Authorized"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="usd", max_length=3)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "provider_payment_intent_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "provider_client_secret",
                    models.CharField(blank=True, max_length=255),
                ),
                ("provider_charge_id", models.CharField(blank=True, max_length=255)),
                ("last_error_message", models.TextField(blank=True)),
                ("processor_response", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_attempts",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("stripe", "Stripe")], default="stripe", max_length=24
                    ),
                ),
                ("event_id", models.CharField(db_index=True, max_length=255)),
                ("event_type", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="payments.paymentattempt",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="paymentwebhookevent",
            constraint=models.UniqueConstraint(
                fields=("provider", "event_id"),
                name="unique_payment_webhook_event_per_provider",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("order", "idempotency_key"),
                name="unique_payment_attempt_idempotency_per_order",
            ),
        ),
    ]
