# Generated by Django 4.2.30 on 2026-04-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispatchassignment",
            options={"ordering": ("-created_at",)},
        ),
    ]
